### ISSUE TITLE
chat_id only accepts i32

### ISSUE THREAD

**Issue by NightsGone** [evan-chaney/telegram-notifyrs#3]
Ran into an instance earlier where the `chat_id` that I was issued was greater than `i32`. As per Telegram [docs](https://core.telegram.org/bots/api#chat), they suggest that the `chat_id` may be greater than 32 bits but smaller than 52 and signed that a 64-bit integer or double-precision float type are safe for storing this identifier.

**Comment by evan-chaney** [comment]
Good call, I didn't run into this issue when making this and just kind of assumed that it covered all chat IDs since the ones I spot-checked worked.

**Comment by NightsGone** [comment]
Just as an FYI would have opened a PR for it but repo settings wouldn't allow me to do so.

**Comment by evan-chaney** [comment]
Ok I'll take a look at that, I didn't mean to restrict PRs.

Just pushed a new tag (v0.1.3) to GitHub and crates.io with the i64 fix.

**Comment by evan-chaney** [comment]
I can't find anywhere that I restricted PRs, did you fork it first and try and open a PR from your repo against this one?

**Comment by NightsGone** [comment]
Too easy!

I did but I might have just been havings issues on my end. If I notice anything again I'll try again and let you know if I still have issues!

I'll close this issue off though since you've pushed the fixed. 😄
